AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function which will alert a slack channel when there is an update available for an opensearch cluster
Transform: AWS::Serverless-2016-10-31

Parameters:
  SlackChannel:
    Type: String
    Default: ""
  SlackWebhookUrl:
    Type: String
    Default: ""
  DomainNameList:
    Type: String
    Default: ""
  EnvironmentIdentifier:
    Type: String
    Default: "default"

Resources:
  osServiceUpdater:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "OS-Service-Update-Notifier-${EnvironmentIdentifier}"
      Description: Lambda function which will alert a slack channel when there is an update available for an opensearch cluster
      Handler: es_service_updater.lambda_handler
      Runtime: python3.13
      CodeUri: src/
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          SLACK_CHANNEL: !Ref SlackChannel
          SLACK_WEBHOOK_URL: !Ref SlackWebhookUrl
          DOMAIN_NAME_LIST: !Ref DomainNameList
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: Permissions
              Action:
              - "cloudformation:ListStacks"
              - "cloudformation:DeleteStack"
              - "iam:DeleteRolePolicy"
              - "iam:DeleteRole"
              - "ec2:DescribeInstances"
              - "es:DescribeElasticsearchDomain"
              - "es:GetCompatibleElasticsearchVersions"
              Effect: Allow
              Resource:
              - '*'
      Events:
        WeeklyReport:
          Type: Schedule
          Properties:
            Schedule: "cron(0 9 ? * MON *)" # Run the weekly report on Mondays at 09:00 GMT
